name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      env:
        TIMESTAMP: ${{ github.event.head_commit.timestamp }}
      run: |
        docker build -t myplugin .
        docker tag myplugin:latest <registry_username>/<repository_name>:${{ env.TIMESTAMP }}
        docker push <registry_username>/<repository_name>:${{ env.TIMESTAMP }}
